import type { Player } from '../types';

export const SEED_PLAYERS: Player[] = [
  {
    id: 'seed-001',
    name: 'Miles Irwin',
    position: 'Skater',
    talent: 4.5,
    vibes: 5,
    notes: 'hilarious on the bench',
    classYear: '2027',
    status: 'available',
    pickNumber: null,
    draftedByTeamId: null,
    captainOfTeamId: null,
  },
  {
    id: 'seed-002',
    name: 'Beckett Bell',
    position: 'Skater',
    talent: 4,
    vibes: 2.5,
    notes: 'great hands, quiet in the room',
    classYear: '2028',
    status: 'available',
    pickNumber: null,
    draftedByTeamId: null,
    captainOfTeamId: null,
  },
  {
    id: 'seed-003',
    name: 'Oliver Mercer',
    position: 'Skater',
    talent: 5,
    vibes: 3.5,
    notes: 'natural leader',
    classYear: '2028',
    status: 'available',
    pickNumber: null,
    draftedByTeamId: null,
    captainOfTeamId: null,
  },
  {
    id: 'seed-004',
    name: 'Mason Brooks',
    position: 'Skater',
    talent: 4,
    vibes: 5,
    notes: 'new to the league, raw talent',
    classYear: '2027',
    status: 'available',
    pickNumber: null,
    draftedByTeamId: null,
    captainOfTeamId: null,
  },
  {
    id: 'seed-005',
    name: 'Vaughn Shaw',
    position: 'Skater',
    talent: 3,
    vibes: 3,
    notes: 'wheels for days, no hands',
    classYear: '2028',
    status: 'available',
    pickNumber: null,
    draftedByTeamId: null,
    captainOfTeamId: null,
  },
  {
    id: 'seed-006',
    name: 'Jasper Hale',
    position: 'Skater',
    talent: 2,
    vibes: 3,
    notes: 'strong forechecker',
    classYear: '2027',
    status: 'available',
    pickNumber: null,
    draftedByTeamId: null,
    captainOfTeamId: null,
  },
  {
    id: 'seed-007',
    name: 'Declan Gray',
    position: 'Skater',
    talent: 3,
    vibes: 5,
    notes: 'natural leader',
    classYear: '2028',
    status: 'available',
    pickNumber: null,
    draftedByTeamId: null,
    captainOfTeamId: null,
  },
  {
    id: 'seed-008',
    name: 'Ethan Dunn',
    position: 'Goalie',
    talent: 2,
    vibes: 4,
    notes: 'reliable, never misses a shift',
    classYear: '2028',
    status: 'available',
    pickNumber: null,
    draftedByTeamId: null,
    captainOfTeamId: null,
  },
  {
    id: 'seed-009',
    name: 'Ryder Dunn',
    position: 'Skater',
    talent: 4,
    vibes: 1,
    notes: 'good in the corners',
    classYear: '2028',
    status: 'available',
    pickNumber: null,
    draftedByTeamId: null,
    captainOfTeamId: null,
  },
  {
    id: 'seed-010',
    name: 'Nash Moran',
    position: 'Skater',
    talent: 2,
    vibes: 5,
    notes: 'solid two-way player',
    classYear: '2027',
    status: 'available',
    pickNumber: null,
    draftedByTeamId: null,
    captainOfTeamId: null,
  },
  {
    id: 'seed-011',
    name: 'Zane Ward',
    position: 'Skater',
    talent: 3,
    vibes: 4,
    notes: 'plays hurt, tough kid',
    classYear: '2028',
    status: 'available',
    pickNumber: null,
    draftedByTeamId: null,
    captainOfTeamId: null,
  },
  {
    id: 'seed-012',
    name: 'Nolan Whitby',
    position: 'Skater',
    talent: 1,
    vibes: 4,
    notes: 'excellent passer',
    classYear: '2027',
    status: 'available',
    pickNumber: null,
    draftedByTeamId: null,
    captainOfTeamId: null,
  },
  {
    id: 'seed-013',
    name: 'Carter Carr',
    position: 'Skater',
    talent: 3,
    vibes: 3,
    notes: 'strong forechecker',
    classYear: '2027',
    status: 'available',
    pickNumber: null,
    draftedByTeamId: null,
    captainOfTeamId: null,
  },
  {
    id: 'seed-014',
    name: 'Spencer Sloan',
    position: 'Skater',
    talent: 4,
    vibes: 2,
    notes: 'great hands, quiet in the room',
    classYear: '2028',
    status: 'available',
    pickNumber: null,
    draftedByTeamId: null,
    captainOfTeamId: null,
  },
  {
    id: 'seed-015',
    name: 'Beckett Lowry',
    position: 'Skater',
    talent: 1,
    vibes: 4,
    notes: 'plays hurt, tough kid',
    classYear: '2027',
    status: 'available',
    pickNumber: null,
    draftedByTeamId: null,
    captainOfTeamId: null,
  },
  {
    id: 'seed-016',
    name: 'Liam Thorne',
    position: 'Skater',
    talent: 2,
    vibes: 2,
    notes: 'needs conditioning',
    classYear: '2028',
    status: 'available',
    pickNumber: null,
    draftedByTeamId: null,
    captainOfTeamId: null,
  },
  {
    id: 'seed-017',
    name: 'Dawson Novak',
    position: 'Skater',
    talent: 4,
    vibes: 3,
    notes: 'new to the league, raw talent',
    classYear: '2028',
    status: 'available',
    pickNumber: null,
    draftedByTeamId: null,
    captainOfTeamId: null,
  },
  {
    id: 'seed-018',
    name: 'Lucas Olsen',
    position: 'Skater',
    talent: 5,
    vibes: 2,
    notes: 'needs conditioning',
    classYear: '2027',
    status: 'available',
    pickNumber: null,
    draftedByTeamId: null,
    captainOfTeamId: null,
  },
  {
    id: 'seed-019',
    name: 'Asher Jensen',
    position: 'Skater',
    talent: 5,
    vibes: 4,
    notes: '',
    classYear: '2028',
    status: 'available',
    pickNumber: null,
    draftedByTeamId: null,
    captainOfTeamId: null,
  },
  {
    id: 'seed-020',
    name: 'Asher Zang',
    position: 'Goalie',
    talent: 4,
    vibes: 2,
    notes: 'new to the league, raw talent',
    classYear: '2028',
    status: 'available',
    pickNumber: null,
    draftedByTeamId: null,
    captainOfTeamId: null,
  },
  {
    id: 'seed-021',
    name: 'Carter Gray',
    position: 'Skater',
    talent: 2,
    vibes: 2,
    notes: 'solid two-way player',
    classYear: '2028',
    status: 'available',
    pickNumber: null,
    draftedByTeamId: null,
    captainOfTeamId: null,
  },
  {
    id: 'seed-022',
    name: 'Ethan Vance',
    position: 'Skater',
    talent: 2,
    vibes: 2,
    notes: 'great hands, quiet in the room',
    classYear: '2027',
    status: 'available',
    pickNumber: null,
    draftedByTeamId: null,
    captainOfTeamId: null,
  },
  {
    id: 'seed-023',
    name: 'Nash Zimmer',
    position: 'Skater',
    talent: 3,
    vibes: 3,
    notes: 'natural leader',
    classYear: '2028',
    status: 'available',
    pickNumber: null,
    draftedByTeamId: null,
    captainOfTeamId: null,
  },
  {
    id: 'seed-024',
    name: 'James Whitby',
    position: 'Skater',
    talent: 5,
    vibes: 5,
    notes: 'solid two-way player',
    classYear: '2028',
    status: 'available',
    pickNumber: null,
    draftedByTeamId: null,
    captainOfTeamId: null,
  },
  {
    id: 'seed-025',
    name: 'Ian Erwin',
    position: 'Skater',
    talent: 3,
    vibes: 2,
    notes: 'wheels for days, no hands',
    classYear: '2027',
    status: 'available',
    pickNumber: null,
    draftedByTeamId: null,
    captainOfTeamId: null,
  },
  {
    id: 'seed-026',
    name: 'Parker Olsen',
    position: 'Skater',
    talent: 1,
    vibes: 1,
    notes: 'new to the league, raw talent',
    classYear: '2027',
    status: 'available',
    pickNumber: null,
    draftedByTeamId: null,
    captainOfTeamId: null,
  },
  {
    id: 'seed-027',
    name: 'Nash Frost',
    position: 'Skater',
    talent: 5,
    vibes: 2,
    notes: 'good vibes, average wheels',
    classYear: '2027',
    status: 'available',
    pickNumber: null,
    draftedByTeamId: null,
    captainOfTeamId: null,
  },
  {
    id: 'seed-028',
    name: 'Oliver Bell',
    position: 'Skater',
    talent: 3,
    vibes: 2,
    notes: 'team glue guy',
    classYear: '2027',
    status: 'available',
    pickNumber: null,
    draftedByTeamId: null,
    captainOfTeamId: null,
  },
  {
    id: 'seed-029',
    name: 'Asher Bauer',
    position: 'Skater',
    talent: 4,
    vibes: 4,
    notes: 'chirps too much',
    classYear: '2028',
    status: 'available',
    pickNumber: null,
    draftedByTeamId: null,
    captainOfTeamId: null,
  },
  {
    id: 'seed-030',
    name: 'Theo Joyce',
    position: 'Skater',
    talent: 5,
    vibes: 3,
    notes: 'team glue guy',
    classYear: '2027',
    status: 'available',
    pickNumber: null,
    draftedByTeamId: null,
    captainOfTeamId: null,
  },
  {
    id: 'seed-031',
    name: 'Miles Dunn',
    position: 'Skater',
    talent: 1,
    vibes: 4,
    notes: 'great hands, quiet in the room',
    classYear: '2028',
    status: 'available',
    pickNumber: null,
    draftedByTeamId: null,
    captainOfTeamId: null,
  },
  {
    id: 'seed-032',
    name: 'Oliver Ward',
    position: 'Goalie',
    talent: 2,
    vibes: 1,
    notes: 'solid two-way player',
    classYear: '2027',
    status: 'available',
    pickNumber: null,
    draftedByTeamId: null,
    captainOfTeamId: null,
  },
  {
    id: 'seed-033',
    name: 'Declan Tate',
    position: 'Skater',
    talent: 4,
    vibes: 5,
    notes: 'chirps too much',
    classYear: '2028',
    status: 'available',
    pickNumber: null,
    draftedByTeamId: null,
    captainOfTeamId: null,
  },
  {
    id: 'seed-034',
    name: 'Reid Ortiz',
    position: 'Skater',
    talent: 5,
    vibes: 3,
    notes: 'team glue guy',
    classYear: '2027',
    status: 'available',
    pickNumber: null,
    draftedByTeamId: null,
    captainOfTeamId: null,
  },
  {
    id: 'seed-035',
    name: 'Jack Ulrich',
    position: 'Skater',
    talent: 4,
    vibes: 2,
    notes: 'cherry picker',
    classYear: '2028',
    status: 'available',
    pickNumber: null,
    draftedByTeamId: null,
    captainOfTeamId: null,
  },
  {
    id: 'seed-036',
    name: 'Levi Walsh',
    position: 'Skater',
    talent: 1,
    vibes: 4,
    notes: 'new to the league, raw talent',
    classYear: '2028',
    status: 'available',
    pickNumber: null,
    draftedByTeamId: null,
    captainOfTeamId: null,
  },
  {
    id: 'seed-037',
    name: 'Dawson Keller',
    position: 'Skater',
    talent: 4,
    vibes: 5,
    notes: 'reliable, never misses a shift',
    classYear: '2027',
    status: 'available',
    pickNumber: null,
    draftedByTeamId: null,
    captainOfTeamId: null,
  },
  {
    id: 'seed-038',
    name: 'Lucas Ingram',
    position: 'Skater',
    talent: 5,
    vibes: 1,
    notes: 'fast but takes bad penalties',
    classYear: '2028',
    status: 'available',
    pickNumber: null,
    draftedByTeamId: null,
    captainOfTeamId: null,
  },
  {
    id: 'seed-039',
    name: 'Rowan Shaw',
    position: 'Skater',
    talent: 3,
    vibes: 4,
    notes: 'chirps too much',
    classYear: '2028',
    status: 'available',
    pickNumber: null,
    draftedByTeamId: null,
    captainOfTeamId: null,
  },
  {
    id: 'seed-040',
    name: 'Keaton Mercer',
    position: 'Skater',
    talent: 3,
    vibes: 2,
    notes: 'reliable, never misses a shift',
    classYear: '2027',
    status: 'available',
    pickNumber: null,
    draftedByTeamId: null,
    captainOfTeamId: null,
  },
  {
    id: 'seed-041',
    name: 'Lucas Zimmer',
    position: 'Skater',
    talent: 4,
    vibes: 2,
    notes: 'good in the corners',
    classYear: '2027',
    status: 'available',
    pickNumber: null,
    draftedByTeamId: null,
    captainOfTeamId: null,
  },
  {
    id: 'seed-042',
    name: 'Beckett Yost',
    position: 'Skater',
    talent: 1,
    vibes: 3,
    notes: 'clutch in overtime',
    classYear: '2027',
    status: 'available',
    pickNumber: null,
    draftedByTeamId: null,
    captainOfTeamId: null,
  },
  {
    id: 'seed-043',
    name: 'Griffin Reeve',
    position: 'Skater',
    talent: 4,
    vibes: 3,
    notes: 'cherry picker',
    classYear: '2028',
    status: 'available',
    pickNumber: null,
    draftedByTeamId: null,
    captainOfTeamId: null,
  },
  {
    id: 'seed-044',
    name: 'Theo Gibbs',
    position: 'Goalie',
    talent: 2,
    vibes: 2,
    notes: 'chirps too much',
    classYear: '2027',
    status: 'available',
    pickNumber: null,
    draftedByTeamId: null,
    captainOfTeamId: null,
  },
  {
    id: 'seed-045',
    name: 'Weston Ellis',
    position: 'Skater',
    talent: 3,
    vibes: 5,
    notes: 'good in the corners',
    classYear: '2027',
    status: 'available',
    pickNumber: null,
    draftedByTeamId: null,
    captainOfTeamId: null,
  },
  {
    id: 'seed-046',
    name: 'Spencer Joyce',
    position: 'Skater',
    talent: 4,
    vibes: 4,
    notes: 'hilarious on the bench',
    classYear: '2028',
    status: 'available',
    pickNumber: null,
    draftedByTeamId: null,
    captainOfTeamId: null,
  },
  {
    id: 'seed-047',
    name: 'Landon Hoyt',
    position: 'Skater',
    talent: 4,
    vibes: 5,
    notes: 'chirps too much',
    classYear: '2028',
    status: 'available',
    pickNumber: null,
    draftedByTeamId: null,
    captainOfTeamId: null,
  },
  {
    id: 'seed-048',
    name: 'Weston Foley',
    position: 'Skater',
    talent: 4,
    vibes: 2,
    notes: 'strong forechecker',
    classYear: '2028',
    status: 'available',
    pickNumber: null,
    draftedByTeamId: null,
    captainOfTeamId: null,
  },
  {
    id: 'seed-049',
    name: 'Ethan Quinn',
    position: 'Skater',
    talent: 1,
    vibes: 5,
    notes: 'big shot, questionable defense',
    classYear: '2028',
    status: 'available',
    pickNumber: null,
    draftedByTeamId: null,
    captainOfTeamId: null,
  },
  {
    id: 'seed-050',
    name: 'Beckett Foley',
    position: 'Skater',
    talent: 4,
    vibes: 4,
    notes: 'cherry picker',
    classYear: '2027',
    status: 'available',
    pickNumber: null,
    draftedByTeamId: null,
    captainOfTeamId: null,
  },
  {
    id: 'seed-051',
    name: 'Bennett Yale',
    position: 'Skater',
    talent: 4,
    vibes: 2,
    notes: 'good vibes, average wheels',
    classYear: '2028',
    status: 'available',
    pickNumber: null,
    draftedByTeamId: null,
    captainOfTeamId: null,
  },
  {
    id: 'seed-052',
    name: 'Jonah Walsh',
    position: 'Skater',
    talent: 2,
    vibes: 2,
    notes: 'solid two-way player',
    classYear: '2027',
    status: 'available',
    pickNumber: null,
    draftedByTeamId: null,
    captainOfTeamId: null,
  },
  {
    id: 'seed-053',
    name: 'Weston Cline',
    position: 'Skater',
    talent: 2,
    vibes: 4,
    notes: 'chirps too much',
    classYear: '2028',
    status: 'available',
    pickNumber: null,
    draftedByTeamId: null,
    captainOfTeamId: null,
  },
  {
    id: 'seed-054',
    name: 'Landon Yale',
    position: 'Skater',
    talent: 3,
    vibes: 5,
    notes: 'reliable, never misses a shift',
    classYear: '2027',
    status: 'available',
    pickNumber: null,
    draftedByTeamId: null,
    captainOfTeamId: null,
  },
  {
    id: 'seed-055',
    name: 'Jasper Gibbs',
    position: 'Skater',
    talent: 3,
    vibes: 4,
    notes: 'team glue guy',
    classYear: '2027',
    status: 'available',
    pickNumber: null,
    draftedByTeamId: null,
    captainOfTeamId: null,
  },
  {
    id: 'seed-056',
    name: 'Tucker Zimmer',
    position: 'Goalie',
    talent: 2,
    vibes: 4,
    notes: 'new to the league, raw talent',
    classYear: '2028',
    status: 'available',
    pickNumber: null,
    draftedByTeamId: null,
    captainOfTeamId: null,
  },
  {
    id: 'seed-057',
    name: 'Weston Moran',
    position: 'Skater',
    talent: 1,
    vibes: 3,
    notes: 'clutch in overtime',
    classYear: '2027',
    status: 'available',
    pickNumber: null,
    draftedByTeamId: null,
    captainOfTeamId: null,
  },
  {
    id: 'seed-058',
    name: 'Ian Quill',
    position: 'Skater',
    talent: 4,
    vibes: 3,
    notes: 'good in the corners',
    classYear: '2027',
    status: 'available',
    pickNumber: null,
    draftedByTeamId: null,
    captainOfTeamId: null,
  },
  {
    id: 'seed-059',
    name: 'Nolan Reeve',
    position: 'Skater',
    talent: 3,
    vibes: 3,
    notes: 'new to the league, raw talent',
    classYear: '2028',
    status: 'available',
    pickNumber: null,
    draftedByTeamId: null,
    captainOfTeamId: null,
  },
  {
    id: 'seed-060',
    name: 'Gavin Payne',
    position: 'Skater',
    talent: 3,
    vibes: 1,
    notes: '',
    classYear: '2027',
    status: 'available',
    pickNumber: null,
    draftedByTeamId: null,
    captainOfTeamId: null,
  },
  {
    id: 'seed-061',
    name: 'Noah Bauer',
    position: 'Skater',
    talent: 3,
    vibes: 2,
    notes: 'clutch in overtime',
    classYear: '2027',
    status: 'available',
    pickNumber: null,
    draftedByTeamId: null,
    captainOfTeamId: null,
  },
  {
    id: 'seed-062',
    name: 'Landon Payne',
    position: 'Skater',
    talent: 4,
    vibes: 3,
    notes: 'new to the league, raw talent',
    classYear: '2027',
    status: 'available',
    pickNumber: null,
    draftedByTeamId: null,
    captainOfTeamId: null,
  },
  {
    id: 'seed-063',
    name: 'Keaton Brooks',
    position: 'Skater',
    talent: 3,
    vibes: 3,
    notes: 'chirps too much',
    classYear: '2028',
    status: 'available',
    pickNumber: null,
    draftedByTeamId: null,
    captainOfTeamId: null,
  },
  {
    id: 'seed-064',
    name: 'Zane Gibbs',
    position: 'Skater',
    talent: 4,
    vibes: 2,
    notes: 'great hands, quiet in the room',
    classYear: '2027',
    status: 'available',
    pickNumber: null,
    draftedByTeamId: null,
    captainOfTeamId: null,
  },
  {
    id: 'seed-065',
    name: 'Reid Bauer',
    position: 'Skater',
    talent: 3,
    vibes: 3,
    notes: 'needs conditioning',
    classYear: '2027',
    status: 'available',
    pickNumber: null,
    draftedByTeamId: null,
    captainOfTeamId: null,
  },
  {
    id: 'seed-066',
    name: 'Theo Quill',
    position: 'Skater',
    talent: 1,
    vibes: 1,
    notes: 'chirps too much',
    classYear: '2027',
    status: 'available',
    pickNumber: null,
    draftedByTeamId: null,
    captainOfTeamId: null,
  },
  {
    id: 'seed-067',
    name: 'Jasper Thorne',
    position: 'Skater',
    talent: 5,
    vibes: 2,
    notes: 'tends to show up late',
    classYear: '2028',
    status: 'available',
    pickNumber: null,
    draftedByTeamId: null,
    captainOfTeamId: null,
  },
  {
    id: 'seed-068',
    name: 'James Ortiz',
    position: 'Goalie',
    talent: 1,
    vibes: 4,
    notes: 'clutch in overtime',
    classYear: '2028',
    status: 'available',
    pickNumber: null,
    draftedByTeamId: null,
    captainOfTeamId: null,
  },
  {
    id: 'seed-069',
    name: 'Hayden Novak',
    position: 'Skater',
    talent: 5,
    vibes: 4,
    notes: 'wheels for days, no hands',
    classYear: '2027',
    status: 'available',
    pickNumber: null,
    draftedByTeamId: null,
    captainOfTeamId: null,
  },
  {
    id: 'seed-070',
    name: 'Tucker Whitby',
    position: 'Skater',
    talent: 3,
    vibes: 4,
    notes: 'team glue guy',
    classYear: '2028',
    status: 'available',
    pickNumber: null,
    draftedByTeamId: null,
    captainOfTeamId: null,
  },
  {
    id: 'seed-071',
    name: 'Levi Mercer',
    position: 'Skater',
    talent: 1,
    vibes: 2,
    notes: 'good in the corners',
    classYear: '2028',
    status: 'available',
    pickNumber: null,
    draftedByTeamId: null,
    captainOfTeamId: null,
  },
  {
    id: 'seed-072',
    name: 'Logan Bauer',
    position: 'Skater',
    talent: 1,
    vibes: 5,
    notes: 'hilarious on the bench',
    classYear: '2027',
    status: 'available',
    pickNumber: null,
    draftedByTeamId: null,
    captainOfTeamId: null,
  },
  {
    id: 'seed-073',
    name: 'Ethan Adams',
    position: 'Skater',
    talent: 2,
    vibes: 2,
    notes: 'strong forechecker',
    classYear: '2027',
    status: 'available',
    pickNumber: null,
    draftedByTeamId: null,
    captainOfTeamId: null,
  },
  {
    id: 'seed-074',
    name: 'James Ellis',
    position: 'Skater',
    talent: 3,
    vibes: 2,
    notes: 'cherry picker',
    classYear: '2027',
    status: 'available',
    pickNumber: null,
    draftedByTeamId: null,
    captainOfTeamId: null,
  },
  {
    id: 'seed-075',
    name: 'Oliver Sloan',
    position: 'Skater',
    talent: 2,
    vibes: 5,
    notes: 'tends to show up late',
    classYear: '2027',
    status: 'available',
    pickNumber: null,
    draftedByTeamId: null,
    captainOfTeamId: null,
  },
  {
    id: 'seed-076',
    name: 'Asher Foley',
    position: 'Skater',
    talent: 4,
    vibes: 3,
    notes: 'tends to show up late',
    classYear: '2027',
    status: 'available',
    pickNumber: null,
    draftedByTeamId: null,
    captainOfTeamId: null,
  },
  {
    id: 'seed-077',
    name: 'Asher Quill',
    position: 'Skater',
    talent: 3,
    vibes: 2,
    notes: 'strong forechecker',
    classYear: '2028',
    status: 'available',
    pickNumber: null,
    draftedByTeamId: null,
    captainOfTeamId: null,
  },
  {
    id: 'seed-078',
    name: 'Levi Erwin',
    position: 'Skater',
    talent: 4,
    vibes: 4,
    notes: '',
    classYear: '2028',
    status: 'available',
    pickNumber: null,
    draftedByTeamId: null,
    captainOfTeamId: null,
  },
  {
    id: 'seed-079',
    name: 'Zane Yost',
    position: 'Skater',
    talent: 2,
    vibes: 4,
    notes: 'fast but takes bad penalties',
    classYear: '2027',
    status: 'available',
    pickNumber: null,
    draftedByTeamId: null,
    captainOfTeamId: null,
  },
  {
    id: 'seed-080',
    name: 'Theo Foley',
    position: 'Goalie',
    talent: 5,
    vibes: 2,
    notes: 'natural leader',
    classYear: '2028',
    status: 'available',
    pickNumber: null,
    draftedByTeamId: null,
    captainOfTeamId: null,
  },
  {
    id: 'seed-081',
    name: 'Spencer Jensen',
    position: 'Skater',
    talent: 1,
    vibes: 2,
    notes: 'reliable, never misses a shift',
    classYear: '2028',
    status: 'available',
    pickNumber: null,
    draftedByTeamId: null,
    captainOfTeamId: null,
  },
  {
    id: 'seed-082',
    name: 'Foster Foley',
    position: 'Skater',
    talent: 2,
    vibes: 4,
    notes: 'wheels for days, no hands',
    classYear: '2028',
    status: 'available',
    pickNumber: null,
    draftedByTeamId: null,
    captainOfTeamId: null,
  },
  {
    id: 'seed-083',
    name: 'Hayden Cline',
    position: 'Skater',
    talent: 1,
    vibes: 1,
    notes: 'chirps too much',
    classYear: '2027',
    status: 'available',
    pickNumber: null,
    draftedByTeamId: null,
    captainOfTeamId: null,
  },
  {
    id: 'seed-084',
    name: 'Nolan Hoyt',
    position: 'Skater',
    talent: 4,
    vibes: 1,
    notes: 'good in the corners',
    classYear: '2028',
    status: 'available',
    pickNumber: null,
    draftedByTeamId: null,
    captainOfTeamId: null,
  },
  {
    id: 'seed-085',
    name: 'Carter Tate',
    position: 'Skater',
    talent: 4,
    vibes: 4,
    notes: '',
    classYear: '2028',
    status: 'available',
    pickNumber: null,
    draftedByTeamId: null,
    captainOfTeamId: null,
  },
  {
    id: 'seed-086',
    name: 'Ryder Mercer',
    position: 'Skater',
    talent: 2,
    vibes: 1,
    notes: 'chirps too much',
    classYear: '2027',
    status: 'available',
    pickNumber: null,
    draftedByTeamId: null,
    captainOfTeamId: null,
  },
  {
    id: 'seed-087',
    name: 'Cole Zang',
    position: 'Skater',
    talent: 1,
    vibes: 1,
    notes: 'needs conditioning',
    classYear: '2027',
    status: 'available',
    pickNumber: null,
    draftedByTeamId: null,
    captainOfTeamId: null,
  },
  {
    id: 'seed-088',
    name: 'Weston Walsh',
    position: 'Skater',
    talent: 4,
    vibes: 1,
    notes: 'strong forechecker',
    classYear: '2028',
    status: 'available',
    pickNumber: null,
    draftedByTeamId: null,
    captainOfTeamId: null,
  },
  {
    id: 'seed-089',
    name: 'Ryder Frost',
    position: 'Skater',
    talent: 1,
    vibes: 1,
    notes: 'team glue guy',
    classYear: '2027',
    status: 'available',
    pickNumber: null,
    draftedByTeamId: null,
    captainOfTeamId: null,
  },
  {
    id: 'seed-090',
    name: 'Reid Brooks',
    position: 'Skater',
    talent: 3,
    vibes: 4,
    notes: 'plays hurt, tough kid',
    classYear: '2027',
    status: 'available',
    pickNumber: null,
    draftedByTeamId: null,
    captainOfTeamId: null,
  },
  {
    id: 'seed-091',
    name: 'Bennett Reeve',
    position: 'Skater',
    talent: 5,
    vibes: 5,
    notes: 'reliable, never misses a shift',
    classYear: '2027',
    status: 'available',
    pickNumber: null,
    draftedByTeamId: null,
    captainOfTeamId: null,
  },
  {
    id: 'seed-092',
    name: 'Cooper Mercer',
    position: 'Goalie',
    talent: 2,
    vibes: 1,
    notes: 'needs conditioning',
    classYear: '2027',
    status: 'available',
    pickNumber: null,
    draftedByTeamId: null,
    captainOfTeamId: null,
  },
  {
    id: 'seed-093',
    name: 'Hayden Joyce',
    position: 'Skater',
    talent: 1,
    vibes: 1,
    notes: 'solid two-way player',
    classYear: '2027',
    status: 'available',
    pickNumber: null,
    draftedByTeamId: null,
    captainOfTeamId: null,
  },
  {
    id: 'seed-094',
    name: 'Henry Yost',
    position: 'Skater',
    talent: 3,
    vibes: 3,
    notes: 'team glue guy',
    classYear: '2028',
    status: 'available',
    pickNumber: null,
    draftedByTeamId: null,
    captainOfTeamId: null,
  },
  {
    id: 'seed-095',
    name: 'Ryder Zimmer',
    position: 'Skater',
    talent: 4,
    vibes: 1,
    notes: 'new to the league, raw talent',
    classYear: '2028',
    status: 'available',
    pickNumber: null,
    draftedByTeamId: null,
    captainOfTeamId: null,
  },
  {
    id: 'seed-096',
    name: 'Quinn Jensen',
    position: 'Skater',
    talent: 4,
    vibes: 1,
    notes: 'strong forechecker',
    classYear: '2027',
    status: 'available',
    pickNumber: null,
    draftedByTeamId: null,
    captainOfTeamId: null,
  },
  {
    id: 'seed-097',
    name: 'Maddox Bell',
    position: 'Skater',
    talent: 3,
    vibes: 2,
    notes: 'good in the corners',
    classYear: '2028',
    status: 'available',
    pickNumber: null,
    draftedByTeamId: null,
    captainOfTeamId: null,
  },
  {
    id: 'seed-098',
    name: 'Griffin Adams',
    position: 'Skater',
    talent: 4,
    vibes: 4,
    notes: 'tends to show up late',
    classYear: '2027',
    status: 'available',
    pickNumber: null,
    draftedByTeamId: null,
    captainOfTeamId: null,
  },
  {
    id: 'seed-099',
    name: 'Ryder Foley',
    position: 'Skater',
    talent: 4,
    vibes: 2,
    notes: 'reliable, never misses a shift',
    classYear: '2027',
    status: 'available',
    pickNumber: null,
    draftedByTeamId: null,
    captainOfTeamId: null,
  },
  {
    id: 'seed-100',
    name: 'Lucas Ward',
    position: 'Skater',
    talent: 4,
    vibes: 3,
    notes: 'natural leader',
    classYear: '2027',
    status: 'available',
    pickNumber: null,
    draftedByTeamId: null,
    captainOfTeamId: null,
  },
];
